In [1]:
import pandas as pd
import numpy as np

In [41]:
playlist = pd.read_csv("recommendations.csv")
playlist_original = pd.read_csv("../phase5_model_development/dataset/playlist_with_segment.csv")
tracks = pd.read_csv("../phase5_model_development/dataset/tracks_new.csv")

In [42]:
# tracks_relevant_columns = tracks[['track_popularity',
#                                   'Early Years', 'Classic Era', 'Golden Era', '2000s', 'Modern Era',
#                                   'Short', 'Medium', 'Long',
#                                   "joy", "calm", "sadness", "fear", "energizing", "dreamy",
#                                   "Instrumental / Ambient Sounds", "Soft Acoustic / Classical", "Orchestral / Soundtrack", "Mid-tempo Pop / Indie", "Upbeat Electronic / Dance", "Slow & Melancholic (Sad Songs)", "Experimental / Jazz Fusion", "Lo-Fi / Chill Vibes"]]

In [43]:
# playlist_original['sentiment_centroid'] = playlist_original['sentiment_centroid'].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))
# playlist_original['genre_centroid'] = playlist_original['genre_centroid'].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

# # Unpack the column into separate columns
# playlist_original[["genre_Instrumental / Ambient Sounds_centroid", "genre_Soft Acoustic / Classical_centroid", "genre_Orchestral / Soundtrack_centroid", "genre_Mid-tempo Pop / Indie_centroid", "genre_Upbeat Electronic / Dance_centroid", "genre_Slow & Melancholic (Sad Songs)_centroid", "genre_Experimental / Jazz Fusion_centroid", "genre_Lo-Fi / Chill Vibes_centroid"]] = pd.DataFrame(playlist_original['genre_centroid'].tolist())

# # Drop the original column if you no longer need it
# playlist_original = playlist_original.drop(columns=['genre_centroid'])

# # Unpack the column into separate columns
# playlist_original[["sentiment_joy_centroid", "sentiment_calm_centroid", "sentiment_sadness_centroid", "sentiment_fear_centroid", "sentiment_energizing_centroid", "sentiment_dreamy_centroid"]] = pd.DataFrame(playlist_original['sentiment_centroid'].tolist())

# # Drop the original column if you no longer need it
# playlist_original = playlist_original.drop(columns=['sentiment_centroid'])

# print(playlist_original)

In [44]:
# playlist_relevant_columns = playlist_original[['popularity_mean', 
#                                       'era_early_years_proportion', 'era_classic_era_proportion', 'era_golden_era_proportion', 'era_2000s_proportion', 'era_modern_era_proportion',
#                                       'length_short_proportion', 'length_medium_proportion', 'length_long_proportion',
#                                       "sent_joy_centroid", "sent_calm_centroid", "sent_sadness_centroid", "sent_fear_centroid", "sent_energizing_centroid", "sent_dreamy_centroid",
#                                       "genre_Instrumental / Ambient Sounds_centroid", "genre_Soft Acoustic / Classical_centroid", "genre_Orchestral / Soundtrack_centroid", "genre_Mid-tempo Pop / Indie_centroid", "genre_Upbeat Electronic / Dance_centroid", "genre_Slow & Melancholic (Sad Songs)_centroid", "genre_Experimental / Jazz Fusion_centroid", "genre_Lo-Fi / Chill Vibes_centroid"]]

In [45]:
playlist_original

,playlist_idx,cluster,dataset_type,name,name_embeddings,num_tracks,track_idx_list,tracks_to_predict,tracks_weights_5dp,num_edits,...,era_early_years_proportion,era_classic_era_proportion,era_golden_era_proportion,era_2000s_proportion,era_modern_era_proportion,length_short_proportion,length_medium_proportion,length_long_proportion,sentiment_centroid,genre_centroid
0,1,1,train,fall '17,[ 1.66989997e-01 -8.01749974e-02 -2.72219986e-...,32,['3689' '207774' '194775' '135193' '218011' '3...,['218708' '242974' '165272' '9418' '221860' '2...,"[('3689', 0.00758), ('207774', 0.00758), ('194...",11,...,0.0,0.000000,0.000000,0.000000,1.000000,0.093750,0.718750,0.187500,[0.09926201 0.10005939 0.18174096 0.19257667 0...,[0.33939356 0.06028851 0.13018671 0.18587857 0...
1,2,3,train,HALLOWEEN,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,10,['160375' '131195' '164629' '147280' '193891' ...,['232845' '111887' '144160' '10663' '216321' '...,"[('160375', 0.1), ('131195', 0.1), ('164629', ...",1,...,0.0,0.500000,0.200000,0.200000,0.100000,0.300000,0.400000,0.300000,[0.05571575 0.04150103 0.1892949 0.18717841 0...,[0.17539133 0.24404486 0.10463579 0.23615809 0...
2,3,3,validation,90s,[-0.32666001 -0.15259001 -0.22385 0.49504 ...,52,['104436' '229428' '25968' '186871' '81592' '1...,['42986' '156208' '73950' '54114' '134077' '21...,"[('104436', 0.00321), ('229428', 0.00321), ('2...",12,...,0.0,0.134615,0.538462,0.288462,0.038462,0.230769,0.519231,0.250000,[0.08737025 0.06740743 0.17658707 0.1728045 0...,[0.17444582 0.08376044 0.23916949 0.23910377 0...
3,4,0,train,Me Like,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,64,['244173' '210510' '9349' '224202' '147251' '3...,['166268' '22122' '211269' '71335' '21853' '19...,"[('244173', 0.00195), ('210510', 0.00195), ('9...",18,...,0.0,0.000000,0.000000,0.062500,0.937500,0.000000,0.375000,0.625000,[0.13178678 0.09436656 0.12261876 0.1025185 0...,[0.37840687 0.07747222 0.15678027 0.08166863 0...
4,5,0,train,Latin Trap,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,73,['194410' '10513' '62267' '196463' '14164' '13...,['209088' '186942' '33032' '27612' '33426' '20...,"[('194410', 0.00556), ('10513', 0.00556), ('62...",4,...,0.0,0.000000,0.000000,0.013699,0.986301,0.013699,0.547945,0.438356,[0.09775545 0.04515955 0.18666905 0.16287565 0...,[0.47525405 0.02912338 0.07773208 0.16155784 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18499,19995,1,train,( r e l a x ),[ 7.05714291e-03 5.35708606e-01 -2.79046565e-...,59,['76313' '158471' '130259' '235274' '3915' '34...,['20667' '215021' '93712' '98021' '14511' '100...,"[('76313', 0.00215), ('158471', 0.00215), ('13...",30,...,0.0,0.000000,0.000000,0.016949,0.983051,0.118644,0.491525,0.389831,[0.05832023 0.06516344 0.20374395 0.19127662 0...,[0.09310669 0.34813044 0.12647131 0.26834955 0...
18500,19996,1,train,Playlist,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,157,['69011' '123049' '192091' '214626' '220817' '...,['147645' '172628' '240055' '34789' '191673' '...,"[('69011', 0.00014), ('123049', 0.00029), ('19...",117,...,0.0,0.000000,0.000000,0.006369,0.993631,0.095541,0.783439,0.121019,[0.08092793 0.07643505 0.20032252 0.20784917 0...,[0.55735539 0.02949404 0.0887953 0.10953456 0...
18501,19997,1,test,🔥🔥🔥,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,161,['140314' '14975' '99481' '234471' '72522' '18...,['1713' '218750' '204173' '42649' '114706' '23...,"[('140314', 0.00018), ('14975', 0.00018), ('99...",74,...,0.0,0.018634,0.024845,0.043478,0.913043,0.149068,0.540373,0.310559,[0.08195065 0.0582571 0.21093627 0.21111458 0...,[0.46500487 0.0394773 0.08956477 0.13854228 0...
18502,19998,3,train,sad times,[ 0.061155 0.620215 -0.1455825 -0.020739...,106,['82540' '34319' '119829' '244328' '232829' '1...,['168352' '115537' '230715' '208147' '33022' '...,"[('82540', 0.00035), ('34319', 0.00035), ('119...",53,...,0.0,0.000000,0.000000,0.207547,0.792453,0.084906,0.452830,0.462264,[0.0772648 0.06080908 0.18441254 0.17055807 0...,[0.28404199 0.28943529 0.0712633 0.14322056 0...
18503,19999,1,test,BOOMIN,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,90,['45959' '231436' '186479' '30051' '2180' '291...,['64550' '218755' '131429' '153501' '190771' '...,"[('45959', 0.00064), ('231436', 0.00064), ('18...",39,...,0.0,0.000000,0.000000,0.022222,0.977778,0.122222,0.588889,0.288889,[0.08513378 0.06830118 0.19256486 0.17856551 0...,[0.52387837 0.04196058 0.08479325 0.12095735 0...

In [46]:
playlist_original = playlist_original.drop(columns=["dataset_type"])

In [47]:
from sklearn.model_selection import train_test_split

# First, split out the 15% final set
remaining, final = train_test_split(
    playlist_original,
    test_size=0.15,
    stratify=playlist_original['cluster'],
    random_state=42
)

# Now from the remaining 85%, split into:
# 65% train --> (65 / 85 ≈ 0.7647)
# 10% val   --> (10 / 85 ≈ 0.1176)
# 10% test  --> (10 / 85 ≈ 0.1176)

train, temp = train_test_split(
    remaining,
    test_size=0.2353,  # 1 - 0.7647 ≈ 0.2353
    stratify=remaining['cluster'],
    random_state=42
)

# Split temp into val and test
val, test = train_test_split(
    temp,
    test_size=0.5,  # Split remaining 23.53% evenly for val and test
    stratify=temp['cluster'],
    random_state=42
)

playlist_original['dataset_type'] = None
playlist_original.loc[train.index, 'dataset_type'] = 'train'
playlist_original.loc[val.index, 'dataset_type'] = 'val'
playlist_original.loc[test.index, 'dataset_type'] = 'test'
playlist_original.loc[final.index, 'dataset_type'] = 'final'

In [48]:
cols = playlist_original.columns.tolist()
cols.insert(2, cols.pop(cols.index('dataset_type')))
playlist_original = playlist_original[cols]
playlist_original

,playlist_idx,cluster,dataset_type,name,name_embeddings,num_tracks,track_idx_list,tracks_to_predict,tracks_weights_5dp,num_edits,...,era_early_years_proportion,era_classic_era_proportion,era_golden_era_proportion,era_2000s_proportion,era_modern_era_proportion,length_short_proportion,length_medium_proportion,length_long_proportion,sentiment_centroid,genre_centroid
0,1,1,train,fall '17,[ 1.66989997e-01 -8.01749974e-02 -2.72219986e-...,32,['3689' '207774' '194775' '135193' '218011' '3...,['218708' '242974' '165272' '9418' '221860' '2...,"[('3689', 0.00758), ('207774', 0.00758), ('194...",11,...,0.0,0.000000,0.000000,0.000000,1.000000,0.093750,0.718750,0.187500,[0.09926201 0.10005939 0.18174096 0.19257667 0...,[0.33939356 0.06028851 0.13018671 0.18587857 0...
1,2,3,test,HALLOWEEN,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,10,['160375' '131195' '164629' '147280' '193891' ...,['232845' '111887' '144160' '10663' '216321' '...,"[('160375', 0.1), ('131195', 0.1), ('164629', ...",1,...,0.0,0.500000,0.200000,0.200000,0.100000,0.300000,0.400000,0.300000,[0.05571575 0.04150103 0.1892949 0.18717841 0...,[0.17539133 0.24404486 0.10463579 0.23615809 0...
2,3,3,train,90s,[-0.32666001 -0.15259001 -0.22385 0.49504 ...,52,['104436' '229428' '25968' '186871' '81592' '1...,['42986' '156208' '73950' '54114' '134077' '21...,"[('104436', 0.00321), ('229428', 0.00321), ('2...",12,...,0.0,0.134615,0.538462,0.288462,0.038462,0.230769,0.519231,0.250000,[0.08737025 0.06740743 0.17658707 0.1728045 0...,[0.17444582 0.08376044 0.23916949 0.23910377 0...
3,4,0,val,Me Like,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,64,['244173' '210510' '9349' '224202' '147251' '3...,['166268' '22122' '211269' '71335' '21853' '19...,"[('244173', 0.00195), ('210510', 0.00195), ('9...",18,...,0.0,0.000000,0.000000,0.062500,0.937500,0.000000,0.375000,0.625000,[0.13178678 0.09436656 0.12261876 0.1025185 0...,[0.37840687 0.07747222 0.15678027 0.08166863 0...
4,5,0,final,Latin Trap,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,73,['194410' '10513' '62267' '196463' '14164' '13...,['209088' '186942' '33032' '27612' '33426' '20...,"[('194410', 0.00556), ('10513', 0.00556), ('62...",4,...,0.0,0.000000,0.000000,0.013699,0.986301,0.013699,0.547945,0.438356,[0.09775545 0.04515955 0.18666905 0.16287565 0...,[0.47525405 0.02912338 0.07773208 0.16155784 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18499,19995,1,train,( r e l a x ),[ 7.05714291e-03 5.35708606e-01 -2.79046565e-...,59,['76313' '158471' '130259' '235274' '3915' '34...,['20667' '215021' '93712' '98021' '14511' '100...,"[('76313', 0.00215), ('158471', 0.00215), ('13...",30,...,0.0,0.000000,0.000000,0.016949,0.983051,0.118644,0.491525,0.389831,[0.05832023 0.06516344 0.20374395 0.19127662 0...,[0.09310669 0.34813044 0.12647131 0.26834955 0...
18500,19996,1,train,Playlist,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,157,['69011' '123049' '192091' '214626' '220817' '...,['147645' '172628' '240055' '34789' '191673' '...,"[('69011', 0.00014), ('123049', 0.00029), ('19...",117,...,0.0,0.000000,0.000000,0.006369,0.993631,0.095541,0.783439,0.121019,[0.08092793 0.07643505 0.20032252 0.20784917 0...,[0.55735539 0.02949404 0.0887953 0.10953456 0...
18501,19997,1,test,🔥🔥🔥,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,161,['140314' '14975' '99481' '234471' '72522' '18...,['1713' '218750' '204173' '42649' '114706' '23...,"[('140314', 0.00018), ('14975', 0.00018), ('99...",74,...,0.0,0.018634,0.024845,0.043478,0.913043,0.149068,0.540373,0.310559,[0.08195065 0.0582571 0.21093627 0.21111458 0...,[0.46500487 0.0394773 0.08956477 0.13854228 0...
18502,19998,3,val,sad times,[ 0.061155 0.620215 -0.1455825 -0.020739...,106,['82540' '34319' '119829' '244328' '232829' '1...,['168352' '115537' '230715' '208147' '33022' '...,"[('82540', 0.00035), ('34319', 0.00035), ('119...",53,...,0.0,0.000000,0.000000,0.207547,0.792453,0.084906,0.452830,0.462264,[0.0772648 0.06080908 0.18441254 0.17055807 0...,[0.28404199 0.28943529 0.0712633 0.14322056 0...
18503,19999,1,final,BOOMIN,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,90,['45959' '231436' '186479' '30051' '2180' '291...,['64550' '218755' '131429' '153501' '190771' '...,"[('45959', 0.00064), ('231436', 0.00064), ('18...",39,...,0.0,0.000000,0.000000,0.022222,0.977778,0.122222,0.588889,0.288889,[0.08513378 0.06830118 0.19256486 0.17856551 0...,[0.52387837 0.04196058 0.08479325 0.12095735 0...

In [49]:
playlist_original = playlist_original.drop(columns=["name","name_embeddings", 'tracks_weights_5dp', 'total_duration'])

In [50]:
# import re

# def convert_string_array_to_list(s):
#     """Convert a string representation of an array into a list of integers."""
#     if isinstance(s, str):  # Handle string case (where it's incorrectly stored)
#         numbers = re.findall(r'\d+', s)  # Extract all numeric values
#         return [int(x) for x in numbers]  # Convert to integers
    
#     elif isinstance(s, np.ndarray):  # Handle NumPy array case
#         return s.astype(int).tolist()
    
#     elif isinstance(s, list):  # Handle lists with possible string numbers
#         return [int(x) for x in s if str(x).isdigit()]
    
#     return []  # Return empty list if the format is unexpected

# # Apply function and debug output
# playlist_original['tracks_to_predict'] = playlist_original['tracks_to_predict'].apply(lambda x: convert_string_array_to_list(x))
# playlist_original['track_idx_list'] = playlist_original['track_idx_list'].apply(lambda x: convert_string_array_to_list(x))

# # Check if the transformation worked
# playlist_original.head(10) # Print first 10 rows

In [51]:
playlist_original

,playlist_idx,cluster,dataset_type,num_tracks,track_idx_list,tracks_to_predict,num_edits,avg_tracks_per_edit,num_artists,popularity_mean,era_early_years_proportion,era_classic_era_proportion,era_golden_era_proportion,era_2000s_proportion,era_modern_era_proportion,length_short_proportion,length_medium_proportion,length_long_proportion,sentiment_centroid,genre_centroid
0,1,1,train,32,['3689' '207774' '194775' '135193' '218011' '3...,['218708' '242974' '165272' '9418' '221860' '2...,11,2.800,37,42.625000,0.0,0.000000,0.000000,0.000000,1.000000,0.093750,0.718750,0.187500,[0.09926201 0.10005939 0.18174096 0.19257667 0...,[0.33939356 0.06028851 0.13018671 0.18587857 0...
1,2,3,test,10,['160375' '131195' '164629' '147280' '193891' ...,['232845' '111887' '144160' '10663' '216321' '...,1,6.667,20,49.300000,0.0,0.500000,0.200000,0.200000,0.100000,0.300000,0.400000,0.300000,[0.05571575 0.04150103 0.1892949 0.18717841 0...,[0.17539133 0.24404486 0.10463579 0.23615809 0...
2,3,3,train,52,['104436' '229428' '25968' '186871' '81592' '1...,['42986' '156208' '73950' '54114' '134077' '21...,12,4.429,56,47.923077,0.0,0.134615,0.538462,0.288462,0.038462,0.230769,0.519231,0.250000,[0.08737025 0.06740743 0.17658707 0.1728045 0...,[0.17444582 0.08376044 0.23916949 0.23910377 0...
3,4,0,val,64,['244173' '210510' '9349' '224202' '147251' '3...,['166268' '22122' '211269' '71335' '21853' '19...,18,3.524,40,43.968750,0.0,0.000000,0.000000,0.062500,0.937500,0.000000,0.375000,0.625000,[0.13178678 0.09436656 0.12261876 0.1025185 0...,[0.37840687 0.07747222 0.15678027 0.08166863 0...
4,5,0,final,73,['194410' '10513' '62267' '196463' '14164' '13...,['209088' '186942' '33032' '27612' '33426' '20...,4,16.600,40,48.643836,0.0,0.000000,0.000000,0.013699,0.986301,0.013699,0.547945,0.438356,[0.09775545 0.04515955 0.18666905 0.16287565 0...,[0.47525405 0.02912338 0.07773208 0.16155784 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18499,19995,1,train,59,['76313' '158471' '130259' '235274' '3915' '34...,['20667' '215021' '93712' '98021' '14511' '100...,30,1.971,62,40.101695,0.0,0.000000,0.000000,0.016949,0.983051,0.118644,0.491525,0.389831,[0.05832023 0.06516344 0.20374395 0.19127662 0...,[0.09310669 0.34813044 0.12647131 0.26834955 0...
18500,19996,1,train,157,['69011' '123049' '192091' '214626' '220817' '...,['147645' '172628' '240055' '34789' '191673' '...,117,1.347,97,41.363057,0.0,0.000000,0.000000,0.006369,0.993631,0.095541,0.783439,0.121019,[0.08092793 0.07643505 0.20032252 0.20784917 0...,[0.55735539 0.02949404 0.0887953 0.10953456 0...
18501,19997,1,test,161,['140314' '14975' '99481' '234471' '72522' '18...,['1713' '218750' '204173' '42649' '114706' '23...,74,2.165,80,50.807453,0.0,0.018634,0.024845,0.043478,0.913043,0.149068,0.540373,0.310559,[0.08195065 0.0582571 0.21093627 0.21111458 0...,[0.46500487 0.0394773 0.08956477 0.13854228 0...
18502,19998,3,val,106,['82540' '34319' '119829' '244328' '232829' '1...,['168352' '115537' '230715' '208147' '33022' '...,53,2.000,70,46.943396,0.0,0.000000,0.000000,0.207547,0.792453,0.084906,0.452830,0.462264,[0.0772648 0.06080908 0.18441254 0.17055807 0...,[0.28404199 0.28943529 0.0712633 0.14322056 0...
18503,19999,1,final,90,['45959' '231436' '186479' '30051' '2180' '291...,['64550' '218755' '131429' '153501' '190771' '...,39,2.326,64,50.111111,0.0,0.000000,0.000000,0.022222,0.977778,0.122222,0.588889,0.288889,[0.08513378 0.06830118 0.19256486 0.17856551 0...,[0.52387837 0.04196058 0.08479325 0.12095735 0...