In [2]:
import pandas as pd
import numpy as np

In [32]:
playlist = pd.read_csv("recommendations.csv")
playlist_original = pd.read_csv("../weighted_playlist.csv")
tracks = pd.read_csv("../phase5_model_development/dataset/tracks_new.csv")

In [19]:
# tracks_relevant_columns = tracks[['track_popularity',
#                                   'Early Years', 'Classic Era', 'Golden Era', '2000s', 'Modern Era',
#                                   'Short', 'Medium', 'Long',
#                                   "joy", "calm", "sadness", "fear", "energizing", "dreamy",
#                                   "Instrumental / Ambient Sounds", "Soft Acoustic / Classical", "Orchestral / Soundtrack", "Mid-tempo Pop / Indie", "Upbeat Electronic / Dance", "Slow & Melancholic (Sad Songs)", "Experimental / Jazz Fusion", "Lo-Fi / Chill Vibes"]]

In [20]:
# playlist_original['sentiment_centroid'] = playlist_original['sentiment_centroid'].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))
# playlist_original['genre_centroid'] = playlist_original['genre_centroid'].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

# # Unpack the column into separate columns
# playlist_original[["genre_Instrumental / Ambient Sounds_centroid", "genre_Soft Acoustic / Classical_centroid", "genre_Orchestral / Soundtrack_centroid", "genre_Mid-tempo Pop / Indie_centroid", "genre_Upbeat Electronic / Dance_centroid", "genre_Slow & Melancholic (Sad Songs)_centroid", "genre_Experimental / Jazz Fusion_centroid", "genre_Lo-Fi / Chill Vibes_centroid"]] = pd.DataFrame(playlist_original['genre_centroid'].tolist())

# # Drop the original column if you no longer need it
# playlist_original = playlist_original.drop(columns=['genre_centroid'])

# # Unpack the column into separate columns
# playlist_original[["sent_joy_centroid", "sent_calm_centroid", "sent_sadness_centroid", "sent_fear_centroid", "sent_energizing_centroid", "sent_dreamy_centroid"]] = pd.DataFrame(playlist_original['sentiment_centroid'].tolist())

# # Drop the original column if you no longer need it
# playlist_original = playlist_original.drop(columns=['sentiment_centroid'])

# print(playlist_original)

In [21]:
# playlist_relevant_columns = playlist_original[['popularity_mean', 
#                                       'era_early_years_proportion', 'era_classic_era_proportion', 'era_golden_era_proportion', 'era_2000s_proportion', 'era_modern_era_proportion',
#                                       'length_short_proportion', 'length_medium_proportion', 'length_long_proportion',
#                                       "sent_joy_centroid", "sent_calm_centroid", "sent_sadness_centroid", "sent_fear_centroid", "sent_energizing_centroid", "sent_dreamy_centroid",
#                                       "genre_Instrumental / Ambient Sounds_centroid", "genre_Soft Acoustic / Classical_centroid", "genre_Orchestral / Soundtrack_centroid", "genre_Mid-tempo Pop / Indie_centroid", "genre_Upbeat Electronic / Dance_centroid", "genre_Slow & Melancholic (Sad Songs)_centroid", "genre_Experimental / Jazz Fusion_centroid", "genre_Lo-Fi / Chill Vibes_centroid"]]

In [33]:
playlist_original

,playlist_idx,num_tracks,track_idx_list,tracks_to_predict,num_edits,avg_tracks_per_edit,num_artists,popularity_mean,era_early_years_proportion,era_classic_era_proportion,era_golden_era_proportion,era_2000s_proportion,era_modern_era_proportion,length_short_proportion,length_medium_proportion,length_long_proportion,sentiment_centroid,genre_centroid
0,1,32,"['3689', '207774', '194775', '135193', '218011...","['218708', '242974', '165272', '9418', '221860...",11,2.800,37,38.441903,0.0,0.00000,0.00000,0.00000,0.99997,0.11616,0.76007,0.12374,[0.10064616 0.10185454 0.16926974 0.19156926 0...,[0.41619244 0.05407289 0.0999797 0.16940492 0...
1,2,10,"['160375', '131195', '164629', '147280', '1938...","['232845', '111887', '144160', '10663', '21632...",1,6.667,20,49.300000,0.0,0.50000,0.20000,0.20000,0.10000,0.30000,0.40000,0.30000,[0.05571575 0.04150103 0.1892949 0.18717841 0...,[0.17539133 0.24404486 0.10463579 0.23615809 0...
2,3,52,"['104436', '229428', '25968', '186871', '81592...","['42986', '156208', '73950', '54114', '134077'...",12,4.429,56,47.394501,0.0,0.12886,0.56160,0.28079,0.02885,0.18208,0.53916,0.27886,[0.07943262 0.06375155 0.18822816 0.18807346 0...,[0.20508151 0.07713566 0.22418737 0.2299858 0...
3,4,64,"['244173', '210510', '9349', '224202', '147251...","['166268', '22122', '211269', '71335', '21853'...",18,3.524,40,46.348273,0.0,0.00000,0.00000,0.07310,0.92695,0.00000,0.32752,0.67253,[0.12718252 0.09709628 0.12344809 0.10363856 0...,[0.37209639 0.09668018 0.16158949 0.08534272 0...
4,5,73,"['194410', '10513', '62267', '196463', '14164'...","['209088', '186942', '33032', '27612', '33426'...",4,16.600,40,50.498665,0.0,0.00000,0.00000,0.02105,0.97902,0.01111,0.59911,0.38985,[0.09931069 0.04668572 0.18617764 0.16440336 0...,[0.49457423 0.02502236 0.07324925 0.14718647 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18499,19995,59,"['76313', '158471', '130259', '235274', '3915'...","['20667', '215021', '93712', '98021', '14511',...",30,1.971,62,39.711463,0.0,0.00000,0.00000,0.01183,0.98818,0.13119,0.53334,0.33548,[0.06410311 0.06492371 0.20241825 0.17793488 0...,[0.10026803 0.32957548 0.12873282 0.29156423 0...
18500,19996,157,"['69011', '123049', '192091', '214626', '22081...","['147645', '172628', '240055', '34789', '19167...",117,1.347,97,41.818626,0.0,0.00000,0.00000,0.00703,0.99295,0.10648,0.76776,0.12574,[0.08032956 0.07504821 0.20359822 0.20855407 0...,[0.56390282 0.02996275 0.08115756 0.10761442 0...
18501,19997,161,"['140314', '14975', '99481', '234471', '72522'...","['1713', '218750', '204173', '42649', '114706'...",74,2.165,80,49.959223,0.0,0.02055,0.02937,0.02144,0.92871,0.15685,0.57095,0.27227,[0.08085026 0.05718929 0.21089904 0.21278627 0...,[0.45144685 0.04204553 0.09114628 0.14899517 0...
18502,19998,106,"['82540', '34319', '119829', '244328', '232829...","['168352', '115537', '230715', '208147', '3302...",53,2.000,70,47.014380,0.0,0.00000,0.00000,0.19705,0.80297,0.07758,0.50978,0.41266,[0.08814644 0.06545712 0.18032715 0.15991462 0...,[0.26325029 0.31147715 0.07485271 0.14886553 0...
18503,19999,90,"['45959', '231436', '186479', '30051', '2180',...","['64550', '218755', '131429', '153501', '19077...",39,2.326,64,52.126607,0.0,0.00000,0.00000,0.02821,0.97181,0.14807,0.57075,0.28120,[0.08659475 0.06540106 0.18887251 0.18111325 0...,[0.51758037 0.0424235 0.08673511 0.12351887 0...

In [23]:
# playlist_original = playlist_original.drop(columns=["dataset_type"])

In [24]:
# from sklearn.model_selection import train_test_split

# # First, split out the 15% final set
# remaining, final = train_test_split(
#     playlist_original,
#     test_size=0.15,
#     stratify=playlist_original['cluster'],
#     random_state=42
# )

# # Now from the remaining 85%, split into:
# # 65% train --> (65 / 85 ≈ 0.7647)
# # 10% val   --> (10 / 85 ≈ 0.1176)
# # 10% test  --> (10 / 85 ≈ 0.1176)

# train, temp = train_test_split(
#     remaining,
#     test_size=0.2353,  # 1 - 0.7647 ≈ 0.2353
#     stratify=remaining['cluster'],
#     random_state=42
# )

# # Split temp into val and test
# val, test = train_test_split(
#     temp,
#     test_size=0.5,  # Split remaining 23.53% evenly for val and test
#     stratify=temp['cluster'],
#     random_state=42
# )

# playlist_original['dataset_type'] = None
# playlist_original.loc[train.index, 'dataset_type'] = 'train'
# playlist_original.loc[val.index, 'dataset_type'] = 'val'
# playlist_original.loc[test.index, 'dataset_type'] = 'test'
# playlist_original.loc[final.index, 'dataset_type'] = 'final'

In [25]:
# cols = playlist_original.columns.tolist()
# cols.insert(2, cols.pop(cols.index('dataset_type')))
# playlist_original = playlist_original[cols]
# playlist_original

In [26]:
# playlist_original = playlist_original.drop(columns=["name","name_embeddings", 'tracks_weights_5dp', 'total_duration'])

In [ ]:
# import re

# def convert_string_array_to_list(s):
#     """Convert a string representation of an array into a list of integers."""
#     if isinstance(s, str):  # Handle string case (where it's incorrectly stored)
#         numbers = re.findall(r'\d+', s)  # Extract all numeric values
#         return [int(x) for x in numbers]  # Convert to integers
    
#     elif isinstance(s, np.ndarray):  # Handle NumPy array case
#         return s.astype(int).tolist()
    
#     elif isinstance(s, list):  # Handle lists with possible string numbers
#         return [int(x) for x in s if str(x).isdigit()]
    
#     return []  # Return empty list if the format is unexpected

# # Apply function and debug output
# playlist_original['tracks_to_predict'] = playlist_original['tracks_to_predict'].apply(lambda x: convert_string_array_to_list(x))
# playlist_original['track_idx_list'] = playlist_original['track_idx_list'].apply(lambda x: convert_string_array_to_list(x))

# # Check if the transformation worked
# playlist_original.head(10) # Print first 10 rows

,playlist_idx,num_tracks,track_idx_list,tracks_to_predict,num_edits,avg_tracks_per_edit,num_artists,popularity_mean,era_early_years_proportion,era_classic_era_proportion,...,sentiment_energizing_centroid,sentiment_dreamy_centroid,genre_Instrumental / Ambient Sounds_centroid,genre_Soft Acoustic / Classical_centroid,genre_Orchestral / Soundtrack_centroid,genre_Mid-tempo Pop / Indie_centroid,genre_Upbeat Electronic / Dance_centroid,genre_Slow & Melancholic (Sad Songs)_centroid,genre_Experimental / Jazz Fusion_centroid,genre_Lo-Fi / Chill Vibes_centroid
0,1,32,"[3689, 207774, 194775, 135193, 218011, 37844, ...","[218708, 242974, 165272, 9418, 221860, 229224,...",11,2.800,37,38.441903,0.0,0.00000,...,0.240730,0.195930,0.416192,0.054073,0.099980,0.169405,0.076664,0.073152,0.081004,0.029529
1,2,10,"[160375, 131195, 164629, 147280, 193891, 17077...","[232845, 111887, 144160, 10663, 216321, 138869...",1,6.667,20,49.300000,0.0,0.50000,...,0.270555,0.255755,0.175391,0.244045,0.104636,0.236158,0.010895,0.107065,0.007359,0.114451
2,3,52,"[104436, 229428, 25968, 186871, 81592, 15947, ...","[42986, 156208, 73950, 54114, 134077, 214967, ...",12,4.429,56,47.394501,0.0,0.12886,...,0.276258,0.204256,0.205082,0.077136,0.224187,0.229986,0.030771,0.048936,0.098481,0.085421
3,4,64,"[244173, 210510, 9349, 224202, 147251, 35498, ...","[166268, 22122, 211269, 71335, 21853, 190702, ...",18,3.524,40,46.348273,0.0,0.00000,...,0.315869,0.232766,0.372096,0.096680,0.161589,0.085343,0.010814,0.059405,0.096185,0.117887
4,5,73,"[194410, 10513, 62267, 196463, 14164, 13405, 1...","[209088, 186942, 33032, 27612, 33426, 201531, ...",4,16.600,40,50.498665,0.0,0.00000,...,0.300442,0.202980,0.494574,0.025022,0.073249,0.147186,0.055752,0.035485,0.065769,0.102962
5,6,16,"[191316, 216283, 108826, 149917, 177254, 23228...","[250306, 36356, 119562, 66146, 206650, 166690,...",9,1.733,23,36.943920,0.0,0.00000,...,0.270296,0.232819,0.262829,0.057191,0.146465,0.169601,0.047628,0.140841,0.164061,0.011383
6,7,75,"[63526, 189533, 78677, 63380, 41539, 67084, 22...","[48557, 142203, 66610, 16213, 112277, 43008, 2...",49,1.518,55,53.671327,0.0,0.01918,...,0.236285,0.204887,0.322062,0.099606,0.143268,0.144797,0.034017,0.099545,0.048968,0.107737
7,8,67,"[14962, 47557, 91553, 104020, 242077, 85947, 1...","[45655, 100810, 250258, 169756, 86872, 117869,...",37,1.791,72,33.360464,0.0,0.00000,...,0.270356,0.215275,0.323030,0.087409,0.114587,0.216776,0.066155,0.090481,0.048566,0.052996
8,9,91,"[22194, 157563, 151356, 87387, 7320, 248495, 2...","[88490, 122326, 87495, 205574, 3345, 191269, 2...",34,2.658,50,44.515391,0.0,0.00336,...,0.277984,0.179939,0.391839,0.069041,0.135011,0.194253,0.058854,0.028145,0.056598,0.066259
9,10,52,"[183059, 19373, 78643, 73807, 86276, 144388, 1...","[89301, 74022, 221104, 218307, 229795, 129045,...",3,20.667,51,39.710183,0.0,0.00000,...,0.255111,0.226661,0.132479,0.084698,0.239656,0.203606,0.084005,0.205981,0.025213,0.024362

In [28]:
playlist_original

,playlist_idx,num_tracks,track_idx_list,tracks_to_predict,num_edits,avg_tracks_per_edit,num_artists,popularity_mean,era_early_years_proportion,era_classic_era_proportion,...,sentiment_energizing_centroid,sentiment_dreamy_centroid,genre_Instrumental / Ambient Sounds_centroid,genre_Soft Acoustic / Classical_centroid,genre_Orchestral / Soundtrack_centroid,genre_Mid-tempo Pop / Indie_centroid,genre_Upbeat Electronic / Dance_centroid,genre_Slow & Melancholic (Sad Songs)_centroid,genre_Experimental / Jazz Fusion_centroid,genre_Lo-Fi / Chill Vibes_centroid
0,1,32,"[3689, 207774, 194775, 135193, 218011, 37844, ...","[218708, 242974, 165272, 9418, 221860, 229224,...",11,2.800,37,38.441903,0.0,0.00000,...,0.240730,0.195930,0.416192,0.054073,0.099980,0.169405,0.076664,0.073152,0.081004,0.029529
1,2,10,"[160375, 131195, 164629, 147280, 193891, 17077...","[232845, 111887, 144160, 10663, 216321, 138869...",1,6.667,20,49.300000,0.0,0.50000,...,0.270555,0.255755,0.175391,0.244045,0.104636,0.236158,0.010895,0.107065,0.007359,0.114451
2,3,52,"[104436, 229428, 25968, 186871, 81592, 15947, ...","[42986, 156208, 73950, 54114, 134077, 214967, ...",12,4.429,56,47.394501,0.0,0.12886,...,0.276258,0.204256,0.205082,0.077136,0.224187,0.229986,0.030771,0.048936,0.098481,0.085421
3,4,64,"[244173, 210510, 9349, 224202, 147251, 35498, ...","[166268, 22122, 211269, 71335, 21853, 190702, ...",18,3.524,40,46.348273,0.0,0.00000,...,0.315869,0.232766,0.372096,0.096680,0.161589,0.085343,0.010814,0.059405,0.096185,0.117887
4,5,73,"[194410, 10513, 62267, 196463, 14164, 13405, 1...","[209088, 186942, 33032, 27612, 33426, 201531, ...",4,16.600,40,50.498665,0.0,0.00000,...,0.300442,0.202980,0.494574,0.025022,0.073249,0.147186,0.055752,0.035485,0.065769,0.102962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18499,19995,59,"[76313, 158471, 130259, 235274, 3915, 34909, 1...","[20667, 215021, 93712, 98021, 14511, 100810, 1...",30,1.971,62,39.711463,0.0,0.00000,...,0.276484,0.214136,0.100268,0.329575,0.128733,0.291564,0.071352,0.041407,0.032271,0.004829
18500,19996,157,"[69011, 123049, 192091, 214626, 220817, 35715,...","[147645, 172628, 240055, 34789, 191673, 245656...",117,1.347,97,41.818626,0.0,0.00000,...,0.239231,0.193239,0.563903,0.029963,0.081158,0.107614,0.036266,0.036284,0.073439,0.071373
18501,19997,161,"[140314, 14975, 99481, 234471, 72522, 184725, ...","[1713, 218750, 204173, 42649, 114706, 230140, ...",74,2.165,80,49.959223,0.0,0.02055,...,0.261372,0.176903,0.451447,0.042046,0.091146,0.148995,0.044532,0.038546,0.115099,0.068189
18502,19998,106,"[82540, 34319, 119829, 244328, 232829, 196631,...","[168352, 115537, 230715, 208147, 33022, 53148,...",53,2.000,70,47.014380,0.0,0.00000,...,0.273508,0.232647,0.263250,0.311477,0.074853,0.148866,0.027848,0.077106,0.027482,0.069118
18503,19999,90,"[45959, 231436, 186479, 30051, 2180, 29149, 84...","[64550, 218755, 131429, 153501, 190771, 153563...",39,2.326,64,52.126607,0.0,0.00000,...,0.296705,0.181313,0.517580,0.042423,0.086735,0.123519,0.031901,0.052659,0.065537,0.079645

In [34]:
playlist_with_segment = pd.read_csv("/Users/ohungchan/Downloads/playlist_final_final.csv")
playlist_with_segment = playlist_with_segment[['playlist_idx', 'dataset_type']]

In [35]:
playlist_original = playlist_with_segment.merge(playlist_original, on='playlist_idx', how='inner')

In [36]:
playlist_original

,playlist_idx,dataset_type,num_tracks,track_idx_list,tracks_to_predict,num_edits,avg_tracks_per_edit,num_artists,popularity_mean,era_early_years_proportion,era_classic_era_proportion,era_golden_era_proportion,era_2000s_proportion,era_modern_era_proportion,length_short_proportion,length_medium_proportion,length_long_proportion,sentiment_centroid,genre_centroid
0,1,train,32,"['3689', '207774', '194775', '135193', '218011...","['218708', '242974', '165272', '9418', '221860...",11,2.800,37,38.441903,0.0,0.00000,0.00000,0.00000,0.99997,0.11616,0.76007,0.12374,[0.10064616 0.10185454 0.16926974 0.19156926 0...,[0.41619244 0.05407289 0.0999797 0.16940492 0...
1,2,test,10,"['160375', '131195', '164629', '147280', '1938...","['232845', '111887', '144160', '10663', '21632...",1,6.667,20,49.300000,0.0,0.50000,0.20000,0.20000,0.10000,0.30000,0.40000,0.30000,[0.05571575 0.04150103 0.1892949 0.18717841 0...,[0.17539133 0.24404486 0.10463579 0.23615809 0...
2,3,train,52,"['104436', '229428', '25968', '186871', '81592...","['42986', '156208', '73950', '54114', '134077'...",12,4.429,56,47.394501,0.0,0.12886,0.56160,0.28079,0.02885,0.18208,0.53916,0.27886,[0.07943262 0.06375155 0.18822816 0.18807346 0...,[0.20508151 0.07713566 0.22418737 0.2299858 0...
3,4,val,64,"['244173', '210510', '9349', '224202', '147251...","['166268', '22122', '211269', '71335', '21853'...",18,3.524,40,46.348273,0.0,0.00000,0.00000,0.07310,0.92695,0.00000,0.32752,0.67253,[0.12718252 0.09709628 0.12344809 0.10363856 0...,[0.37209639 0.09668018 0.16158949 0.08534272 0...
4,5,final,73,"['194410', '10513', '62267', '196463', '14164'...","['209088', '186942', '33032', '27612', '33426'...",4,16.600,40,50.498665,0.0,0.00000,0.00000,0.02105,0.97902,0.01111,0.59911,0.38985,[0.09931069 0.04668572 0.18617764 0.16440336 0...,[0.49457423 0.02502236 0.07324925 0.14718647 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18499,19995,train,59,"['76313', '158471', '130259', '235274', '3915'...","['20667', '215021', '93712', '98021', '14511',...",30,1.971,62,39.711463,0.0,0.00000,0.00000,0.01183,0.98818,0.13119,0.53334,0.33548,[0.06410311 0.06492371 0.20241825 0.17793488 0...,[0.10026803 0.32957548 0.12873282 0.29156423 0...
18500,19996,train,157,"['69011', '123049', '192091', '214626', '22081...","['147645', '172628', '240055', '34789', '19167...",117,1.347,97,41.818626,0.0,0.00000,0.00000,0.00703,0.99295,0.10648,0.76776,0.12574,[0.08032956 0.07504821 0.20359822 0.20855407 0...,[0.56390282 0.02996275 0.08115756 0.10761442 0...
18501,19997,test,161,"['140314', '14975', '99481', '234471', '72522'...","['1713', '218750', '204173', '42649', '114706'...",74,2.165,80,49.959223,0.0,0.02055,0.02937,0.02144,0.92871,0.15685,0.57095,0.27227,[0.08085026 0.05718929 0.21089904 0.21278627 0...,[0.45144685 0.04204553 0.09114628 0.14899517 0...
18502,19998,val,106,"['82540', '34319', '119829', '244328', '232829...","['168352', '115537', '230715', '208147', '3302...",53,2.000,70,47.014380,0.0,0.00000,0.00000,0.19705,0.80297,0.07758,0.50978,0.41266,[0.08814644 0.06545712 0.18032715 0.15991462 0...,[0.26325029 0.31147715 0.07485271 0.14886553 0...
18503,19999,final,90,"['45959', '231436', '186479', '30051', '2180',...","['64550', '218755', '131429', '153501', '19077...",39,2.326,64,52.126607,0.0,0.00000,0.00000,0.02821,0.97181,0.14807,0.57075,0.28120,[0.08659475 0.06540106 0.18887251 0.18111325 0...,[0.51758037 0.0424235 0.08673511 0.12351887 0...